//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml;
using System.Xml.Serialization;

namespace VsSdk.UForm
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class AccessDeniedFault
    {
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UFormSummary
    {
        
        private long uFormIdField;
        
        private string dateField;
        
        private UFormStatusType statusField;
        
        private bool statusFieldSpecified;
        
        private string numberField;
        
        private string cancelReasonField;
        
        private string registrationNumberField;
        
        private System.DateTime lastUpdateDateField;
        
        private bool lastUpdateDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long uFormId
        {
            get
            {
                return this.uFormIdField;
            }
            set
            {
                this.uFormIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UFormStatusType status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cancelReason
        {
            get
            {
                return this.cancelReasonField;
            }
            set
            {
                this.cancelReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string registrationNumber
        {
            get
            {
                return this.registrationNumberField;
            }
            set
            {
                this.registrationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime lastUpdateDate
        {
            get
            {
                return this.lastUpdateDateField;
            }
            set
            {
                this.lastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastUpdateDateSpecified
        {
            get
            {
                return this.lastUpdateDateFieldSpecified;
            }
            set
            {
                this.lastUpdateDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public enum UFormStatusType
    {
        
        /// <remarks/>
        CREATED,
        
        /// <remarks/>
        IN_PROCESSING,
        
        /// <remarks/>
        PROCESSED,
        
        /// <remarks/>
        WAIT_INSTOCK,
        
        /// <remarks/>
        WAIT_DOCUMENT,
        
        /// <remarks/>
        CANCELED,
        
        /// <remarks/>
        FAILED,
        
        /// <remarks/>
        DRAFT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UFormStatusResponse
    {
        
        private UFormSummary[] uFormSummaryListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("uFormSummary", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UFormSummary[] uFormSummaryList
        {
            get
            {
                return this.uFormSummaryListField;
            }
            set
            {
                this.uFormSummaryListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UFormUploadInfo
    {
        
        private string uFormBodyField;
        
        private string versionField;
        
        private string signatureField;
        
        private SignatureType signatureTypeField;

        [XmlIgnore]
        public string uFormBodyRaw
        {
            get
            {
                return this.uFormBodyField;
            }
            set
            {
                this.uFormBodyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlCDataSection uFormBody
        {
            get
            {
                var dummy = new XmlDocument();
                return dummy.CreateCDataSection(this.uFormBodyField);
            }
            set
            {
                throw new NotImplementedException();
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SignatureType signatureType
        {
            get
            {
                return this.signatureTypeField;
            }
            set
            {
                this.signatureTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public enum SignatureType
    {
        
        /// <remarks/>
        COMPANY,
        
        /// <remarks/>
        OPERATOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UFormIdWithReason
    {
        
        private long idField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UFormQueryUpdatesRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UploadUFormRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UFormErrorByIdRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UFormByIdWithReasonRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UFormByIdRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public abstract partial class AbstractSessionAwareRequest
    {
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UFormQueryUpdatesRequest : AbstractSessionAwareRequest
    {
        
        private System.DateTime lastEventDateField;
        
        private long lastUFormIdField;
        
        private bool lastUFormIdFieldSpecified;
        
        private int limitField;
        
        private bool limitFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime lastEventDate
        {
            get
            {
                return this.lastEventDateField;
            }
            set
            {
                this.lastEventDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long lastUFormId
        {
            get
            {
                return this.lastUFormIdField;
            }
            set
            {
                this.lastUFormIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastUFormIdSpecified
        {
            get
            {
                return this.lastUFormIdFieldSpecified;
            }
            set
            {
                this.lastUFormIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int limit
        {
            get
            {
                return this.limitField;
            }
            set
            {
                this.limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool limitSpecified
        {
            get
            {
                return this.limitFieldSpecified;
            }
            set
            {
                this.limitFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UploadUFormRequest : AbstractSessionAwareRequest
    {
        
        private UFormUploadInfo[] uFormInfoListField;
        
        private string x509CertificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("uFormInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UFormUploadInfo[] uFormInfoList
        {
            get
            {
                return this.uFormInfoListField;
            }
            set
            {
                this.uFormInfoListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string x509Certificate
        {
            get
            {
                return this.x509CertificateField;
            }
            set
            {
                this.x509CertificateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UFormErrorByIdRequest : AbstractSessionAwareRequest
    {
        
        private long[] idListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public long[] idList
        {
            get
            {
                return this.idListField;
            }
            set
            {
                this.idListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UFormByIdWithReasonRequest : AbstractSessionAwareRequest
    {
        
        private string signatureField;
        
        private string x509CertificateField;
        
        private UFormIdWithReason[] idWithReasonListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string x509Certificate
        {
            get
            {
                return this.x509CertificateField;
            }
            set
            {
                this.x509CertificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("uFormIdWithReason", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UFormIdWithReason[] idWithReasonList
        {
            get
            {
                return this.idWithReasonListField;
            }
            set
            {
                this.idWithReasonListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UFormByIdRequest : AbstractSessionAwareRequest
    {
        
        private long[] idListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public long[] idList
        {
            get
            {
                return this.idListField;
            }
            set
            {
                this.idListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class BusinessFault
    {
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class SessionClosedFault
    {
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace.vstore", ConfigurationName="VsSdk.UForm.UFormWebService")]
    public interface UFormWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.AccessDeniedFault), Action="", Name="accessDeniedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.BusinessFault), Action="", Name="businessException")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.SessionClosedFault), Action="", Name="sessionClosedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractSessionAwareRequest))]
        System.Threading.Tasks.Task<VsSdk.UForm.queryUFormStatusByIdResponse> queryUFormStatusByIdAsync(VsSdk.UForm.queryUFormStatusById request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.AccessDeniedFault), Action="", Name="accessDeniedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.BusinessFault), Action="", Name="businessException")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.SessionClosedFault), Action="", Name="sessionClosedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractSessionAwareRequest))]
        System.Threading.Tasks.Task<VsSdk.UForm.cancelUFormByIdResponse> cancelUFormByIdAsync(VsSdk.UForm.cancelUFormById request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.AccessDeniedFault), Action="", Name="accessDeniedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.BusinessFault), Action="", Name="businessException")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.SessionClosedFault), Action="", Name="sessionClosedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractSessionAwareRequest))]
        System.Threading.Tasks.Task<VsSdk.UForm.queryUFormByIdResponse> queryUFormByIdAsync(VsSdk.UForm.queryUFormById request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.AccessDeniedFault), Action="", Name="accessDeniedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.BusinessFault), Action="", Name="businessException")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.SessionClosedFault), Action="", Name="sessionClosedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractSessionAwareRequest))]
        System.Threading.Tasks.Task<VsSdk.UForm.queryUFormErrorByIdResponse> queryUFormErrorByIdAsync(VsSdk.UForm.queryUFormErrorById request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.AccessDeniedFault), Action="", Name="accessDeniedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.BusinessFault), Action="", Name="businessException")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.SessionClosedFault), Action="", Name="sessionClosedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractSessionAwareRequest))]
        System.Threading.Tasks.Task<VsSdk.UForm.uploadUFormResponse1> uploadUFormAsync(VsSdk.UForm.uploadUForm request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.BusinessFault), Action="", Name="businessException")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.AccessDeniedFault), Action="", Name="accessDeniedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.UForm.SessionClosedFault), Action="", Name="sessionClosedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractSessionAwareRequest))]
        System.Threading.Tasks.Task<VsSdk.UForm.queryUpdatesResponse> queryUpdatesAsync(VsSdk.UForm.queryUpdates request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryUFormStatusById
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.UForm.UFormByIdRequest queryUFormStatusByIdRequest;
        
        public queryUFormStatusById()
        {
        }
        
        public queryUFormStatusById(VsSdk.UForm.UFormByIdRequest queryUFormStatusByIdRequest)
        {
            this.queryUFormStatusByIdRequest = queryUFormStatusByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryUFormStatusByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queryUFormStatusByIdResponse", Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.UForm.UFormStatusResponse queryUFormStatusByIdResponse1;
        
        public queryUFormStatusByIdResponse()
        {
        }
        
        public queryUFormStatusByIdResponse(VsSdk.UForm.UFormStatusResponse queryUFormStatusByIdResponse1)
        {
            this.queryUFormStatusByIdResponse1 = queryUFormStatusByIdResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UFormChangeStatusResponse
    {
        
        private UFormChangeStatusResult[] resultListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("changeStatusResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UFormChangeStatusResult[] resultList
        {
            get
            {
                return this.resultListField;
            }
            set
            {
                this.resultListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UFormChangeStatusResult
    {
        
        private UFormSummary uFormSummaryField;
        
        private bool isChangedField;
        
        private string errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UFormSummary uFormSummary
        {
            get
            {
                return this.uFormSummaryField;
            }
            set
            {
                this.uFormSummaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isChanged
        {
            get
            {
                return this.isChangedField;
            }
            set
            {
                this.isChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelUFormById
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.UForm.UFormByIdWithReasonRequest cancelUFormByIdRequest;
        
        public cancelUFormById()
        {
        }
        
        public cancelUFormById(VsSdk.UForm.UFormByIdWithReasonRequest cancelUFormByIdRequest)
        {
            this.cancelUFormByIdRequest = cancelUFormByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelUFormByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cancelUFormByIdResponse", Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.UForm.UFormChangeStatusResponse cancelUFormByIdResponse1;
        
        public cancelUFormByIdResponse()
        {
        }
        
        public cancelUFormByIdResponse(VsSdk.UForm.UFormChangeStatusResponse cancelUFormByIdResponse1)
        {
            this.cancelUFormByIdResponse1 = cancelUFormByIdResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class QueryUFormResponse
    {
        
        private bool lastBlockField;
        
        private int currPageField;
        
        private int recordsCountField;
        
        private UFormInfo[] uFormInfoListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool lastBlock
        {
            get
            {
                return this.lastBlockField;
            }
            set
            {
                this.lastBlockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int currPage
        {
            get
            {
                return this.currPageField;
            }
            set
            {
                this.currPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int recordsCount
        {
            get
            {
                return this.recordsCountField;
            }
            set
            {
                this.recordsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("uFormInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UFormInfo[] uFormInfoList
        {
            get
            {
                return this.uFormInfoListField;
            }
            set
            {
                this.uFormInfoListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UFormInfo
    {
        
        private string uFormBodyField;
        
        private long uFormIdField;
        
        private bool uFormIdFieldSpecified;
        
        private System.DateTime inputDateField;
        
        private bool inputDateFieldSpecified;
        
        private System.DateTime lastUpdateDateField;
        
        private bool lastUpdateDateFieldSpecified;
        
        private bool signatureValidField;
        
        private bool signatureValidFieldSpecified;
        
        private UFormStatusType statusField;
        
        private bool statusFieldSpecified;
        
        private string cancelReasonField;
        
        private string versionField;
        
        private string signatureField;
        
        private SignatureType signatureTypeField;
        
        private string registrationNumberField;
        
        private string creatorLoginField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uFormBody
        {
            get
            {
                return this.uFormBodyField;
            }
            set
            {
                this.uFormBodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long uFormId
        {
            get
            {
                return this.uFormIdField;
            }
            set
            {
                this.uFormIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uFormIdSpecified
        {
            get
            {
                return this.uFormIdFieldSpecified;
            }
            set
            {
                this.uFormIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime inputDate
        {
            get
            {
                return this.inputDateField;
            }
            set
            {
                this.inputDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inputDateSpecified
        {
            get
            {
                return this.inputDateFieldSpecified;
            }
            set
            {
                this.inputDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime lastUpdateDate
        {
            get
            {
                return this.lastUpdateDateField;
            }
            set
            {
                this.lastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastUpdateDateSpecified
        {
            get
            {
                return this.lastUpdateDateFieldSpecified;
            }
            set
            {
                this.lastUpdateDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool signatureValid
        {
            get
            {
                return this.signatureValidField;
            }
            set
            {
                this.signatureValidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signatureValidSpecified
        {
            get
            {
                return this.signatureValidFieldSpecified;
            }
            set
            {
                this.signatureValidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UFormStatusType status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cancelReason
        {
            get
            {
                return this.cancelReasonField;
            }
            set
            {
                this.cancelReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SignatureType signatureType
        {
            get
            {
                return this.signatureTypeField;
            }
            set
            {
                this.signatureTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string registrationNumber
        {
            get
            {
                return this.registrationNumberField;
            }
            set
            {
                this.registrationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creatorLogin
        {
            get
            {
                return this.creatorLoginField;
            }
            set
            {
                this.creatorLoginField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryUFormById
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.UForm.UFormByIdRequest queryUFormByIdRequest;
        
        public queryUFormById()
        {
        }
        
        public queryUFormById(VsSdk.UForm.UFormByIdRequest queryUFormByIdRequest)
        {
            this.queryUFormByIdRequest = queryUFormByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryUFormByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queryUFormByIdResponse", Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.UForm.QueryUFormResponse queryUFormByIdResponse1;
        
        public queryUFormByIdResponse()
        {
        }
        
        public queryUFormByIdResponse(VsSdk.UForm.QueryUFormResponse queryUFormByIdResponse1)
        {
            this.queryUFormByIdResponse1 = queryUFormByIdResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UFormErrorByIdResponse
    {
        
        private UFormErrorInfo[] uFormErrorInfoListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("uFormError", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UFormErrorInfo[] uFormErrorInfoList
        {
            get
            {
                return this.uFormErrorInfoListField;
            }
            set
            {
                this.uFormErrorInfoListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UFormErrorInfo
    {
        
        private long uFormIdField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long uFormId
        {
            get
            {
                return this.uFormIdField;
            }
            set
            {
                this.uFormIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Error[] errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class Error
    {
        
        private string propertyField;
        
        private string errorCodeField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryUFormErrorById
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.UForm.UFormErrorByIdRequest uFormErrorByIdRequest;
        
        public queryUFormErrorById()
        {
        }
        
        public queryUFormErrorById(VsSdk.UForm.UFormErrorByIdRequest uFormErrorByIdRequest)
        {
            this.uFormErrorByIdRequest = uFormErrorByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryUFormErrorByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.UForm.UFormErrorByIdResponse uFormErrorByIdResponse;
        
        public queryUFormErrorByIdResponse()
        {
        }
        
        public queryUFormErrorByIdResponse(VsSdk.UForm.UFormErrorByIdResponse uFormErrorByIdResponse)
        {
            this.uFormErrorByIdResponse = uFormErrorByIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UploadUFormResponse
    {
        
        private UploadUFormResult[] acceptedListField;
        
        private UploadUFormResult[] declinedListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("uploadUFormResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UploadUFormResult[] acceptedList
        {
            get
            {
                return this.acceptedListField;
            }
            set
            {
                this.acceptedListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("uploadUFormResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UploadUFormResult[] declinedList
        {
            get
            {
                return this.declinedListField;
            }
            set
            {
                this.declinedListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UploadUFormResult
    {
        
        private Error[] errorListField;
        
        private Notification[] notificationListField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string numberField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Error[] errorList
        {
            get
            {
                return this.errorListField;
            }
            set
            {
                this.errorListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("notification", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Notification[] notificationList
        {
            get
            {
                return this.notificationListField;
            }
            set
            {
                this.notificationListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class Notification
    {
        
        private string propertyField;
        
        private string notificationCodeField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string notificationCode
        {
            get
            {
                return this.notificationCodeField;
            }
            set
            {
                this.notificationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadUForm
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.UForm.UploadUFormRequest uploadUFormRequest;
        
        public uploadUForm()
        {
        }
        
        public uploadUForm(VsSdk.UForm.UploadUFormRequest uploadUFormRequest)
        {
            this.uploadUFormRequest = uploadUFormRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadUFormResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.UForm.UploadUFormResponse uploadUFormResponse;
        
        public uploadUFormResponse1()
        {
        }
        
        public uploadUFormResponse1(VsSdk.UForm.UploadUFormResponse uploadUFormResponse)
        {
            this.uploadUFormResponse = uploadUFormResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class UFormQueryUpdatesResponse
    {
        
        private System.DateTime lastEventDateField;
        
        private long lastUFormIdField;
        
        private bool lastUFormIdFieldSpecified;
        
        private bool lastBlockField;
        
        private UFormInfo[] uFormInfoListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime lastEventDate
        {
            get
            {
                return this.lastEventDateField;
            }
            set
            {
                this.lastEventDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long lastUFormId
        {
            get
            {
                return this.lastUFormIdField;
            }
            set
            {
                this.lastUFormIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastUFormIdSpecified
        {
            get
            {
                return this.lastUFormIdFieldSpecified;
            }
            set
            {
                this.lastUFormIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool lastBlock
        {
            get
            {
                return this.lastBlockField;
            }
            set
            {
                this.lastBlockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("uFormInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UFormInfo[] uFormInfoList
        {
            get
            {
                return this.uFormInfoListField;
            }
            set
            {
                this.uFormInfoListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryUpdates
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.UForm.UFormQueryUpdatesRequest queryUpdatesRequest;
        
        public queryUpdates()
        {
        }
        
        public queryUpdates(VsSdk.UForm.UFormQueryUpdatesRequest queryUpdatesRequest)
        {
            this.queryUpdatesRequest = queryUpdatesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryUpdatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.UForm.UFormQueryUpdatesResponse uFormQueryUpdatesResponse;
        
        public queryUpdatesResponse()
        {
        }
        
        public queryUpdatesResponse(VsSdk.UForm.UFormQueryUpdatesResponse uFormQueryUpdatesResponse)
        {
            this.uFormQueryUpdatesResponse = uFormQueryUpdatesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface UFormWebServiceChannel : VsSdk.UForm.UFormWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class UFormWebServiceClient : System.ServiceModel.ClientBase<VsSdk.UForm.UFormWebService>, VsSdk.UForm.UFormWebService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UFormWebServiceClient() : 
                base(UFormWebServiceClient.GetDefaultBinding(), UFormWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.UFormWebServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UFormWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(UFormWebServiceClient.GetBindingForEndpoint(endpointConfiguration), UFormWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UFormWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UFormWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UFormWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UFormWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UFormWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<VsSdk.UForm.queryUFormStatusByIdResponse> queryUFormStatusByIdAsync(VsSdk.UForm.queryUFormStatusById request)
        {
            return base.Channel.queryUFormStatusByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsSdk.UForm.cancelUFormByIdResponse> cancelUFormByIdAsync(VsSdk.UForm.cancelUFormById request)
        {
            return base.Channel.cancelUFormByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsSdk.UForm.queryUFormByIdResponse> queryUFormByIdAsync(VsSdk.UForm.queryUFormById request)
        {
            return base.Channel.queryUFormByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsSdk.UForm.queryUFormErrorByIdResponse> queryUFormErrorByIdAsync(VsSdk.UForm.queryUFormErrorById request)
        {
            return base.Channel.queryUFormErrorByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsSdk.UForm.uploadUFormResponse1> uploadUFormAsync(VsSdk.UForm.uploadUForm request)
        {
            return base.Channel.uploadUFormAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsSdk.UForm.queryUpdatesResponse> queryUpdatesAsync(VsSdk.UForm.queryUpdates request)
        {
            return base.Channel.queryUpdatesAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UFormWebServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UFormWebServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://esf.gov.kz:8443/esf-web/vstore-ws/api1/UFormWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UFormWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.UFormWebServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UFormWebServiceClient.GetEndpointAddress(EndpointConfiguration.UFormWebServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            UFormWebServicePort,
        }
    }
}
