//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsSdk.VstoreSession
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class AccessDeniedFault
    {
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class createSessionResponse
    {
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class createSessionRequest
    {
        
        private string tinField;
        
        private long projectCodeField;
        
        private bool projectCodeFieldSpecified;
        
        private businessProfileType businessProfileTypeField;
        
        private bool businessProfileTypeFieldSpecified;
        
        private string x509CertificateField;
        
        private SourceType sourceTypeField;
        
        private bool sourceTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tin
        {
            get
            {
                return this.tinField;
            }
            set
            {
                this.tinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long projectCode
        {
            get
            {
                return this.projectCodeField;
            }
            set
            {
                this.projectCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool projectCodeSpecified
        {
            get
            {
                return this.projectCodeFieldSpecified;
            }
            set
            {
                this.projectCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public businessProfileType businessProfileType
        {
            get
            {
                return this.businessProfileTypeField;
            }
            set
            {
                this.businessProfileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool businessProfileTypeSpecified
        {
            get
            {
                return this.businessProfileTypeFieldSpecified;
            }
            set
            {
                this.businessProfileTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string x509Certificate
        {
            get
            {
                return this.x509CertificateField;
            }
            set
            {
                this.x509CertificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public SourceType sourceType
        {
            get
            {
                return this.sourceTypeField;
            }
            set
            {
                this.sourceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sourceTypeSpecified
        {
            get
            {
                return this.sourceTypeFieldSpecified;
            }
            set
            {
                this.sourceTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public enum businessProfileType
    {
        
        /// <remarks/>
        ADMIN_ENTERPRISE,
        
        /// <remarks/>
        USER,
        
        /// <remarks/>
        ENTREPRENEUR,
        
        /// <remarks/>
        ENTREPRENEUR_USER,
        
        /// <remarks/>
        INDIVIDUAL,
        
        /// <remarks/>
        LAWYER,
        
        /// <remarks/>
        BAILIFF,
        
        /// <remarks/>
        MEDIATOR,
        
        /// <remarks/>
        NOTARY,
        
        /// <remarks/>
        LAWYER_USER,
        
        /// <remarks/>
        BAILIFF_USER,
        
        /// <remarks/>
        MEDIATOR_USER,
        
        /// <remarks/>
        NOTARY_USER,
        
        /// <remarks/>
        PROJECT_ADMIN,
        
        /// <remarks/>
        PROJECT_USER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public enum SourceType
    {
        
        /// <remarks/>
        BROWSER,
        
        /// <remarks/>
        DESKTOP,
        
        /// <remarks/>
        ERP_1C,
        
        /// <remarks/>
        ERP_SAP,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class BusinessFault
    {
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class SessionClosedFault
    {
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="namespace.vstore", ConfigurationName="VsSdk.VstoreSession.VstoreSessionService")]
    public interface VstoreSessionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.VstoreSession.AccessDeniedFault), Action="", Name="accessDeniedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.VstoreSession.BusinessFault), Action="", Name="businessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VsSdk.VstoreSession.createSessionResponse1> createSessionAsync(VsSdk.VstoreSession.createSession request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VsSdk.VstoreSession.currentSessionStatusResponse1> currentSessionStatusAsync(VsSdk.VstoreSession.currentSessionStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VsSdk.VstoreSession.closeSessionResponse1> closeSessionAsync(VsSdk.VstoreSession.closeSession request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.VstoreSession.AccessDeniedFault), Action="", Name="accessDeniedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.VstoreSession.BusinessFault), Action="", Name="businessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VsSdk.VstoreSession.closeSessionByCredentialsResponse> closeSessionByCredentialsAsync(VsSdk.VstoreSession.closeSessionByCredentials request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.VstoreSession.SessionClosedFault), Action="", Name="sessionClosedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VsSdk.VstoreSession.currentUserProfilesResponse1> currentUserProfilesAsync(VsSdk.VstoreSession.currentUserProfiles request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VsSdk.VstoreSession.SessionClosedFault), Action="", Name="sessionClosedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VsSdk.VstoreSession.currentUserResponse1> currentUserAsync(VsSdk.VstoreSession.currentUser request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createSession
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.VstoreSession.createSessionRequest createSessionRequest;
        
        public createSession()
        {
        }
        
        public createSession(VsSdk.VstoreSession.createSessionRequest createSessionRequest)
        {
            this.createSessionRequest = createSessionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createSessionResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.VstoreSession.createSessionResponse createSessionResponse;
        
        public createSessionResponse1()
        {
        }
        
        public createSessionResponse1(VsSdk.VstoreSession.createSessionResponse createSessionResponse)
        {
            this.createSessionResponse = createSessionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class currentSessionStatusRequest : AbstractSessionAwareRequest
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(currentUserRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(currentUserProfilesRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(closeSessionRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(currentSessionStatusRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public abstract partial class AbstractSessionAwareRequest
    {
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class currentUserRequest : AbstractSessionAwareRequest
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class currentUserProfilesRequest : AbstractSessionAwareRequest
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class closeSessionRequest : AbstractSessionAwareRequest
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class currentSessionStatusResponse
    {
        
        private sessionStatus statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sessionStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public enum sessionStatus
    {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        CLOSED,
        
        /// <remarks/>
        NOT_FOUND,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currentSessionStatus
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.VstoreSession.currentSessionStatusRequest currentSessionStatusRequest;
        
        public currentSessionStatus()
        {
        }
        
        public currentSessionStatus(VsSdk.VstoreSession.currentSessionStatusRequest currentSessionStatusRequest)
        {
            this.currentSessionStatusRequest = currentSessionStatusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currentSessionStatusResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.VstoreSession.currentSessionStatusResponse currentSessionStatusResponse;
        
        public currentSessionStatusResponse1()
        {
        }
        
        public currentSessionStatusResponse1(VsSdk.VstoreSession.currentSessionStatusResponse currentSessionStatusResponse)
        {
            this.currentSessionStatusResponse = currentSessionStatusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class closeSessionResponse
    {
        
        private sessionStatus statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sessionStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeSession
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.VstoreSession.closeSessionRequest closeSessionRequest;
        
        public closeSession()
        {
        }
        
        public closeSession(VsSdk.VstoreSession.closeSessionRequest closeSessionRequest)
        {
            this.closeSessionRequest = closeSessionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeSessionResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.VstoreSession.closeSessionResponse closeSessionResponse;
        
        public closeSessionResponse1()
        {
        }
        
        public closeSessionResponse1(VsSdk.VstoreSession.closeSessionResponse closeSessionResponse)
        {
            this.closeSessionResponse = closeSessionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class closeSessionByCredentialsRequest
    {
        
        private string tinField;
        
        private long projectCodeField;
        
        private bool projectCodeFieldSpecified;
        
        private businessProfileType businessProfileTypeField;
        
        private bool businessProfileTypeFieldSpecified;
        
        private string x509CertificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tin
        {
            get
            {
                return this.tinField;
            }
            set
            {
                this.tinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long projectCode
        {
            get
            {
                return this.projectCodeField;
            }
            set
            {
                this.projectCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool projectCodeSpecified
        {
            get
            {
                return this.projectCodeFieldSpecified;
            }
            set
            {
                this.projectCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public businessProfileType businessProfileType
        {
            get
            {
                return this.businessProfileTypeField;
            }
            set
            {
                this.businessProfileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool businessProfileTypeSpecified
        {
            get
            {
                return this.businessProfileTypeFieldSpecified;
            }
            set
            {
                this.businessProfileTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string x509Certificate
        {
            get
            {
                return this.x509CertificateField;
            }
            set
            {
                this.x509CertificateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeSessionByCredentials
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.VstoreSession.closeSessionByCredentialsRequest closeSessionByCredentialsRequest;
        
        public closeSessionByCredentials()
        {
        }
        
        public closeSessionByCredentials(VsSdk.VstoreSession.closeSessionByCredentialsRequest closeSessionByCredentialsRequest)
        {
            this.closeSessionByCredentialsRequest = closeSessionByCredentialsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeSessionByCredentialsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.VstoreSession.closeSessionResponse closeSessionResponse;
        
        public closeSessionByCredentialsResponse()
        {
        }
        
        public closeSessionByCredentialsResponse(VsSdk.VstoreSession.closeSessionResponse closeSessionResponse)
        {
            this.closeSessionResponse = closeSessionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class currentUserProfilesResponse
    {
        
        private profileInfo[] profileInfoListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public profileInfo[] profileInfoList
        {
            get
            {
                return this.profileInfoListField;
            }
            set
            {
                this.profileInfoListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class profileInfo
    {
        
        private string iinField;
        
        private string tinField;
        
        private businessProfileType businessProfileTypeField;
        
        private bool businessProfileTypeFieldSpecified;
        
        private userStatusType statusField;
        
        private bool statusFieldSpecified;
        
        private profileType typeField;
        
        private bool typeFieldSpecified;
        
        private projectParticipantType projectParticipantTypeField;
        
        private bool projectParticipantTypeFieldSpecified;
        
        private long projectCodeField;
        
        private bool projectCodeFieldSpecified;
        
        private string projectNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string iin
        {
            get
            {
                return this.iinField;
            }
            set
            {
                this.iinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tin
        {
            get
            {
                return this.tinField;
            }
            set
            {
                this.tinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public businessProfileType businessProfileType
        {
            get
            {
                return this.businessProfileTypeField;
            }
            set
            {
                this.businessProfileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool businessProfileTypeSpecified
        {
            get
            {
                return this.businessProfileTypeFieldSpecified;
            }
            set
            {
                this.businessProfileTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public userStatusType status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public profileType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public projectParticipantType projectParticipantType
        {
            get
            {
                return this.projectParticipantTypeField;
            }
            set
            {
                this.projectParticipantTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool projectParticipantTypeSpecified
        {
            get
            {
                return this.projectParticipantTypeFieldSpecified;
            }
            set
            {
                this.projectParticipantTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long projectCode
        {
            get
            {
                return this.projectCodeField;
            }
            set
            {
                this.projectCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool projectCodeSpecified
        {
            get
            {
                return this.projectCodeFieldSpecified;
            }
            set
            {
                this.projectCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string projectName
        {
            get
            {
                return this.projectNameField;
            }
            set
            {
                this.projectNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public enum userStatusType
    {
        
        /// <remarks/>
        ACTIVE,
        
        /// <remarks/>
        BLOCKED,
        
        /// <remarks/>
        ENTERPRISE_ADMIN_CHANGE_BLOCKED,
        
        /// <remarks/>
        ENTERPRISE_BLOCKED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public enum profileType
    {
        
        /// <remarks/>
        GENERAL,
        
        /// <remarks/>
        PROJECT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public enum projectParticipantType
    {
        
        /// <remarks/>
        ATTORNEY,
        
        /// <remarks/>
        OPERATOR,
        
        /// <remarks/>
        TRUSTER,
        
        /// <remarks/>
        CONTRACTOR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currentUserProfiles
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.VstoreSession.currentUserProfilesRequest currentUserProfilesRequest;
        
        public currentUserProfiles()
        {
        }
        
        public currentUserProfiles(VsSdk.VstoreSession.currentUserProfilesRequest currentUserProfilesRequest)
        {
            this.currentUserProfilesRequest = currentUserProfilesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currentUserProfilesResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.VstoreSession.currentUserProfilesResponse currentUserProfilesResponse;
        
        public currentUserProfilesResponse1()
        {
        }
        
        public currentUserProfilesResponse1(VsSdk.VstoreSession.currentUserProfilesResponse currentUserProfilesResponse)
        {
            this.currentUserProfilesResponse = currentUserProfilesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class currentUserResponse
    {
        
        private User userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public User user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class User
    {
        
        private string loginField;
        
        private string emailField;
        
        private string mobileField;
        
        private string issueDateField;
        
        private string issuedByField;
        
        private string passportNumField;
        
        private userStatusType statusField;
        
        private string reasonField;
        
        private Taxpayer taxpayerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string issueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string issuedBy
        {
            get
            {
                return this.issuedByField;
            }
            set
            {
                this.issuedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string passportNum
        {
            get
            {
                return this.passportNumField;
            }
            set
            {
                this.passportNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public userStatusType status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public Taxpayer taxpayer
        {
            get
            {
                return this.taxpayerField;
            }
            set
            {
                this.taxpayerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class Taxpayer
    {
        
        private string tinField;
        
        private string nameRuField;
        
        private string lastNameRuField;
        
        private string firstNameRuField;
        
        private string middleNameRuField;
        
        private string lastNameKzField;
        
        private string firstNameKzField;
        
        private string middleNameKzField;
        
        private string nameKzField;
        
        private string addressRuField;
        
        private string addressKzField;
        
        private string certificateSeriesField;
        
        private string certificateNumField;
        
        private bool residentField;
        
        private Taxpayer headOfficeField;
        
        private EnterpriseType typeField;
        
        private bool typeFieldSpecified;
        
        private bool resourceUserField;
        
        private SettlementAccount[] accountsField;
        
        private string enterpriseAdministratorField;
        
        private string budgetIinField;
        
        private string kogdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tin
        {
            get
            {
                return this.tinField;
            }
            set
            {
                this.tinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nameRu
        {
            get
            {
                return this.nameRuField;
            }
            set
            {
                this.nameRuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string lastNameRu
        {
            get
            {
                return this.lastNameRuField;
            }
            set
            {
                this.lastNameRuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string firstNameRu
        {
            get
            {
                return this.firstNameRuField;
            }
            set
            {
                this.firstNameRuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string middleNameRu
        {
            get
            {
                return this.middleNameRuField;
            }
            set
            {
                this.middleNameRuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string lastNameKz
        {
            get
            {
                return this.lastNameKzField;
            }
            set
            {
                this.lastNameKzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string firstNameKz
        {
            get
            {
                return this.firstNameKzField;
            }
            set
            {
                this.firstNameKzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string middleNameKz
        {
            get
            {
                return this.middleNameKzField;
            }
            set
            {
                this.middleNameKzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nameKz
        {
            get
            {
                return this.nameKzField;
            }
            set
            {
                this.nameKzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string addressRu
        {
            get
            {
                return this.addressRuField;
            }
            set
            {
                this.addressRuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string addressKz
        {
            get
            {
                return this.addressKzField;
            }
            set
            {
                this.addressKzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string certificateSeries
        {
            get
            {
                return this.certificateSeriesField;
            }
            set
            {
                this.certificateSeriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string certificateNum
        {
            get
            {
                return this.certificateNumField;
            }
            set
            {
                this.certificateNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool resident
        {
            get
            {
                return this.residentField;
            }
            set
            {
                this.residentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public Taxpayer headOffice
        {
            get
            {
                return this.headOfficeField;
            }
            set
            {
                this.headOfficeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public EnterpriseType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public bool resourceUser
        {
            get
            {
                return this.resourceUserField;
            }
            set
            {
                this.resourceUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("settlementAccount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SettlementAccount[] accounts
        {
            get
            {
                return this.accountsField;
            }
            set
            {
                this.accountsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string enterpriseAdministrator
        {
            get
            {
                return this.enterpriseAdministratorField;
            }
            set
            {
                this.enterpriseAdministratorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string budgetIin
        {
            get
            {
                return this.budgetIinField;
            }
            set
            {
                this.budgetIinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string kogd
        {
            get
            {
                return this.kogdField;
            }
            set
            {
                this.kogdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public enum EnterpriseType
    {
        
        /// <remarks/>
        NOT_SET,
        
        /// <remarks/>
        INDIVIDUAL,
        
        /// <remarks/>
        INDIVIDUAL_ENTREPRENEUR,
        
        /// <remarks/>
        PRIVATE_ENTERPRISE,
        
        /// <remarks/>
        STATE_ENTERPRISE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class SettlementAccount
    {
        
        private long idField;
        
        private string taxpayerTinField;
        
        private Bank bankField;
        
        private int accountTypeField;
        
        private bool accountTypeFieldSpecified;
        
        private string accountField;
        
        private System.DateTime dateOpenField;
        
        private bool dateOpenFieldSpecified;
        
        private System.DateTime dateCloseField;
        
        private bool dateCloseFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string taxpayerTin
        {
            get
            {
                return this.taxpayerTinField;
            }
            set
            {
                this.taxpayerTinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Bank bank
        {
            get
            {
                return this.bankField;
            }
            set
            {
                this.bankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int accountType
        {
            get
            {
                return this.accountTypeField;
            }
            set
            {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accountTypeSpecified
        {
            get
            {
                return this.accountTypeFieldSpecified;
            }
            set
            {
                this.accountTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string account
        {
            get
            {
                return this.accountField;
            }
            set
            {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime dateOpen
        {
            get
            {
                return this.dateOpenField;
            }
            set
            {
                this.dateOpenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateOpenSpecified
        {
            get
            {
                return this.dateOpenFieldSpecified;
            }
            set
            {
                this.dateOpenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime dateClose
        {
            get
            {
                return this.dateCloseField;
            }
            set
            {
                this.dateCloseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCloseSpecified
        {
            get
            {
                return this.dateCloseFieldSpecified;
            }
            set
            {
                this.dateCloseFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="namespace.vstore")]
    public partial class Bank
    {
        
        private long idField;
        
        private string nameRuField;
        
        private string nameKzField;
        
        private string bikField;
        
        private string codeField;
        
        private string tinField;
        
        private string rnnField;
        
        private bool activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nameRu
        {
            get
            {
                return this.nameRuField;
            }
            set
            {
                this.nameRuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nameKz
        {
            get
            {
                return this.nameKzField;
            }
            set
            {
                this.nameKzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string bik
        {
            get
            {
                return this.bikField;
            }
            set
            {
                this.bikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tin
        {
            get
            {
                return this.tinField;
            }
            set
            {
                this.tinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string rnn
        {
            get
            {
                return this.rnnField;
            }
            set
            {
                this.rnnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currentUser
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.VstoreSession.currentUserRequest currentUserRequest;
        
        public currentUser()
        {
        }
        
        public currentUser(VsSdk.VstoreSession.currentUserRequest currentUserRequest)
        {
            this.currentUserRequest = currentUserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class currentUserResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="namespace.vstore", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VsSdk.VstoreSession.currentUserResponse currentUserResponse;
        
        public currentUserResponse1()
        {
        }
        
        public currentUserResponse1(VsSdk.VstoreSession.currentUserResponse currentUserResponse)
        {
            this.currentUserResponse = currentUserResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface VstoreSessionServiceChannel : VsSdk.VstoreSession.VstoreSessionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class VstoreSessionServiceClient : System.ServiceModel.ClientBase<VsSdk.VstoreSession.VstoreSessionService>, VsSdk.VstoreSession.VstoreSessionService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VstoreSessionServiceClient() : 
                base(VstoreSessionServiceClient.GetDefaultBinding(), VstoreSessionServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.VstoreSessionServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VstoreSessionServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(VstoreSessionServiceClient.GetBindingForEndpoint(endpointConfiguration), VstoreSessionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VstoreSessionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VstoreSessionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VstoreSessionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VstoreSessionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VstoreSessionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<VsSdk.VstoreSession.createSessionResponse1> createSessionAsync(VsSdk.VstoreSession.createSession request)
        {
            return base.Channel.createSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsSdk.VstoreSession.currentSessionStatusResponse1> currentSessionStatusAsync(VsSdk.VstoreSession.currentSessionStatus request)
        {
            return base.Channel.currentSessionStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsSdk.VstoreSession.closeSessionResponse1> closeSessionAsync(VsSdk.VstoreSession.closeSession request)
        {
            return base.Channel.closeSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsSdk.VstoreSession.closeSessionByCredentialsResponse> closeSessionByCredentialsAsync(VsSdk.VstoreSession.closeSessionByCredentials request)
        {
            return base.Channel.closeSessionByCredentialsAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsSdk.VstoreSession.currentUserProfilesResponse1> currentUserProfilesAsync(VsSdk.VstoreSession.currentUserProfiles request)
        {
            return base.Channel.currentUserProfilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsSdk.VstoreSession.currentUserResponse1> currentUserAsync(VsSdk.VstoreSession.currentUser request)
        {
            return base.Channel.currentUserAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VstoreSessionServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VstoreSessionServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://esf.gov.kz:8443/esf-web/vstore-ws/api1/VstoreSessionService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return VstoreSessionServiceClient.GetBindingForEndpoint(EndpointConfiguration.VstoreSessionServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return VstoreSessionServiceClient.GetEndpointAddress(EndpointConfiguration.VstoreSessionServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            VstoreSessionServicePort,
        }
    }
}
