using Microsoft.EntityFrameworkCore.Migrations;

namespace TCO.SNT.DataAccess.SqlServer.Migrations
{
    public partial class CurrenciesAndTopCurrencies : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Currencies",
                columns: table => new
                {
                    Code = table.Column<string>(maxLength: 3, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Currencies", x => x.Code);
                });

            migrationBuilder.CreateTable(
                name: "FavouriteCurrencies",
                columns: table => new
                {
                    CurrencyId = table.Column<string>(maxLength: 3, nullable: false),
                    SortOrder = table.Column<byte>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FavouriteCurrencies", x => x.CurrencyId);
                    table.ForeignKey(
                        name: "FK_FavouriteCurrencies_Currencies_CurrencyId",
                        column: x => x.CurrencyId,
                        principalTable: "Currencies",
                        principalColumn: "Code");
                });

            migrationBuilder.InsertData(
                table: "Currencies",
                column: "Code",
                values: new object[]
                {
                    "KZT",
                    "KPW",
                    "MWK",
                    "MAD",
                    "ATS",
                    "KGS",
                    "BSD",
                    "LSL",
                    "MVR",
                    "SRD",
                    "CDF",
                    "FRF",
                    "GRD",
                    "AFN",
                    "LKR",
                    "HTG",
                    "ILS",
                    "QAR",
                    "EGP",
                    "AED",
                    "GIP",
                    "AOA",
                    "EUR",
                    "KYD",
                    "LVL",
                    "DOP",
                    "MXN",
                    "PYG",
                    "RWF",
                    "SOS",
                    "UYI",
                    "NLG",
                    "PTE",
                    "BWP",
                    "RUB",
                    "ECS",
                    "GHS",
                    "HUF",
                    "KES",
                    "MGF",
                    "MUR",
                    "TJS",
                    "TZS",
                    "CUC",
                    "FKI",
                    "SDG",
                    "KRW",
                    "MZN",
                    "IEP",
                    "AMD",
                    "XDR",
                    "CUP",
                    "GYD",
                    "MTL",
                    "NAD",
                    "TPE",
                    "SKK",
                    "MKD",
                    "BAM",
                    "CNY",
                    "SVC",
                    "PHP",
                    "ISK",
                    "SAR",
                    "BZD",
                    "CVE",
                    "BEF",
                    "SIT",
                    "PGK",
                    "GEL",
                    "BGN",
                    "PLN",
                    "BRL",
                    "ITL",
                    "DZD",
                    "BMD",
                    "HKD",
                    "JOD",
                    "AWG",
                    "THB",
                    "MYR",
                    "UYU",
                    "BTN",
                    "MNT",
                    "VUV",
                    "TOP",
                    "VEF",
                    "LBP",
                    "UAK",
                    "ALL",
                    "BBD",
                    "CAD",
                    "KHR",
                    "ARS",
                    "FIM",
                    "ESP",
                    "BHD",
                    "FJD",
                    "LRD",
                    "SZL",
                    "XEU",
                    "TRY",
                    "UZS",
                    "BOB",
                    "BYR",
                    "INR",
                    "NZD",
                    "STD",
                    "ZWL",
                    "TTD",
                    "WST",
                    "SEK",
                    "EEK",
                    "HRK",
                    "GBP",
                    "RON",
                    "ANG",
                    "LUF",
                    "LYD",
                    "CYP",
                    "MRO",
                    "PAB",
                    "LAK",
                    "DEM",
                    "TMT",
                    "IDR",
                    "SCR",
                    "FKP",
                    "YER",
                    "XCD",
                    "AZM",
                    "ADP",
                    "SHP",
                    "ZAR",
                    "RSD",
                    "CHF",
                    "CZK",
                    "HNL",
                    "AUD",
                    "GNF",
                    "IRR",
                    "NGN",
                    "CLP",
                    "JMD",
                    "XAF",
                    "DKK",
                    "SBD",
                    "IQD",
                    "PKR",
                    "ZMK",
                    "ERN",
                    "MDL",
                    "ZRN",
                    "MGA",
                    "OMR",
                    "SLL",
                    "sel",
                    "BDT",
                    "DJF",
                    "NPR",
                    "VND",
                    "TWD",
                    "XPF",
                    "LTL",
                    "JPY",
                    "PEN",
                    "GWP",
                    "UGS",
                    "YUN",
                    "BND",
                    "SYP",
                    "USD",
                    "NOK",
                    "CRC",
                    "ETB",
                    "XOF",
                    "GTQ",
                    "TND",
                    "COU",
                    "SGD",
                    "MMK",
                    "COP",
                    "GMD",
                    "MOP",
                    "KWD",
                    "BIF",
                    "NIO",
                    "BYN"
                });

            migrationBuilder.Sql("insert into FavouriteCurrencies (CurrencyId, SortOrder) values ('KZT', 1), ('RUB', 2), ('USD', 3), ('EUR', 4), ('GBP', 5);");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FavouriteCurrencies");

            migrationBuilder.DropTable(
                name: "Currencies");
        }
    }
}
