//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCO.SNT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UFormTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UFormTypeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCO.SNT.Resources.UFormTypeResource", typeof(UFormTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остатки.
        /// </summary>
        public static string BALANCE {
            get {
                return ResourceManager.GetString("BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличение остатков.
        /// </summary>
        public static string BALANCE_CORRECTION {
            get {
                return ResourceManager.GetString("BALANCE_CORRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детализация.
        /// </summary>
        public static string DETAILING {
            get {
                return ResourceManager.GetString("DETAILING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДТ - Декларация на товары.
        /// </summary>
        public static string DT {
            get {
                return ResourceManager.GetString("DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЭСФ.
        /// </summary>
        public static string ESF {
            get {
                return ResourceManager.GetString("ESF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФНО 328.00 - Форма налоговой отчетности.
        /// </summary>
        public static string FNO {
            get {
                return ResourceManager.GetString("FNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма Детализации Импорта.
        /// </summary>
        public static string IMPORT_DETAILING {
            get {
                return ResourceManager.GetString("IMPORT_DETAILING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чек ККМ.
        /// </summary>
        public static string KKM {
            get {
                return ResourceManager.GetString("KKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производство.
        /// </summary>
        public static string MANUFACTURE {
            get {
                return ResourceManager.GetString("MANUFACTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутреннее перемещение.
        /// </summary>
        public static string MOVEMENT {
            get {
                return ResourceManager.GetString("MOVEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Физическая метка.
        /// </summary>
        public static string PHYSICAL_LABEL {
            get {
                return ResourceManager.GetString("PHYSICAL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реорганизация.
        /// </summary>
        public static string REORGANIZATION {
            get {
                return ResourceManager.GetString("REORGANIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списание.
        /// </summary>
        public static string WRITE_OFF {
            get {
                return ResourceManager.GetString("WRITE_OFF", resourceCulture);
            }
        }
    }
}
